services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\System\:
        resource: '../'

    App\System\ParamConverter\JsonConverter:
        tags:
            - { name: 'request.param_converter', converter: 'json_converter' }
