doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            User:
                dir: '%kernel.project_dir%/src/User/Infrastructure/Orm'
                prefix: 'App\User\Infrastructure\Orm'
            UserAccount:
                dir: '%kernel.project_dir%/src/Account/Infrastructure/Orm'
                prefix: 'App\Account\Infrastructure\Orm'
            Transaction:
                dir: '%kernel.project_dir%/src/Transaction/Infrastructure/Orm'
                prefix: 'App\Transaction\Infrastructure\Orm'
            Stats:
                dir: '%kernel.project_dir%/src/Statistic/Infrastructure/Orm'
                prefix: 'App\Statistic\Infrastructure\Orm'

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
