services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Account\:
        resource: '../'
        exclude:
            - '../Http/Transaction.php'
            - '../Domain/Event/'
            - '../Domain/Account.php'
            - '../Domain/AccountId.php'

    account.snapshot_repository:
        class: App\Shared\EventSourcing\DoctrineSnapshotRepository
        arguments:
            $aggregateIdClass: 'App\Account\Domain\AccountId'
            $tableName: 'account_snapshots'

    account.aggregate_root_repository:
        class: EventSauce\EventSourcing\EventSourcedAggregateRootRepository
        arguments:
            $aggregateRootClassName: 'App\Account\Domain\Account'
            $messageRepository: '@account.message_repository'
            $dispatcher: '@account.message_dispatcher'

    App\Account\Domain\Handler\AccountSynchronizer:
        tags: ['account.consumer']

    account.message_dispatcher:
        class: App\Shared\EventSourcing\SynchronousMessageDispatcher
        arguments:
            - !tagged_iterator account.consumer

    account.message_repository:
        class: EventSauce\MessageRepository\DoctrineMessageRepository\DoctrineUuidV4MessageRepository
        arguments:
            $tableName: 'account_events'

    App\Account\Infrastructure\AccountRepository:
        arguments:
            $messageRepository: '@account.message_repository'
            $snapshotRepository: '@account.snapshot_repository'
            $aggregateRootRepository: '@account.aggregate_root_repository'

