services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    App\Statistic\:
        resource: '../'
        exclude:
            - '../config/'

    App\Statistic\Domain\Projection\DailyStatsRecorder:
        tags: ['account.consumer']

    App\Statistic\Domain\Projection\CategoryTracker:
        tags: ['account.consumer']