imports:
    - { resource: ../src/System/config/services.yaml }
    - { resource: ../src/Shared/config/services.yaml }
    - { resource: ../src/Account/config/services.yaml }
    - { resource: ../src/User/config/services.yaml }
    - { resource: ../src/Transaction/config/services.yaml }
    - { resource: ../src/Statistic/config/services.yaml }
